# Generated by Django 4.2 on 2023-04-07 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=55)),
                ('cpf', models.CharField(max_length=11)),
                ('saldo', models.FloatField(db_column='SALDO', default=0)),
                ('agencia', models.CharField(max_length=6)),
                ('num_conta', models.CharField(max_length=6)),
            ],
        ),
    ]
