# Generated by Django 4.2 on 2024-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacorrente',
            name='status',
            field=models.CharField(choices=[('ativo', 'ativo'), ('cancelado', 'cancelado'), ('bloqueado', 'bloqueado')], default='ativo'),
        ),
    ]
