# Generated by Django 4.2 on 2023-04-29 00:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_contacorrente_options_contacorrente_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4)),
                ('num_conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='conta.contacorrente')),
                ('valor', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
