# Generated by Django 4.2 on 2023-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_boleto_id_alter_boleto_num_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='agencia',
            field=models.CharField(default=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='num_conta',
            field=models.CharField(default='0001', max_length=6),
        ),
    ]
