# Generated by Django 4.2 on 2023-05-03 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_boleto_agencia_alter_boleto_num_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='num_conta',
        ),
        migrations.AddField(
            model_name='boleto',
            name='conta_corrente',
            field=models.ForeignKey(db_column='CONTA_CORRENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='conta.contacorrente'),
        ),
    ]
