# Generated by Django 4.2 on 2023-05-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_remove_boleto_agencia_remove_boleto_num_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='conta_corrente',
            field=models.ForeignKey(db_column='CONTA_CORRENT_ID', on_delete=django.db.models.deletion.CASCADE, to='conta.contacorrente'),
        ),
    ]
