# Generated by Django 4.2 on 2024-06-18 13:57

import common_modules.definir_vencimento_cobranca_use_case
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('data_vencimento', models.DateField(default=common_modules.definir_vencimento_cobranca_use_case.DefinirVencimentoCobrancaUseCase.execute)),
                ('status', models.CharField(choices=[('pagamento_pendente', 'pagamento pendente'), ('pago', 'pago'), ('vencido', 'vencido'), ('cancelado', 'cancelado')], default='pagamento_pendente', max_length=20)),
                ('conta_corrente', models.ForeignKey(db_column='CONTA_CORRENT_ID', on_delete=django.db.models.deletion.CASCADE, to='conta.contacorrente')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoBoleto',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boleto_cobranca', to='boleto.boleto')),
                ('conta_sacado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_sacado', to='conta.contacorrente')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
