# Generated by Django 4.2 on 2023-05-03 01:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0008_delete_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('conta_corrente', models.ForeignKey(db_column='CONTA_CORRENT_ID', on_delete=django.db.models.deletion.CASCADE, to='conta.contacorrente')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
