# Generated by Django 4.2 on 2023-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='status',
            field=models.CharField(default='Pendente', max_length=100),
        ),
    ]
