# Generated by Django 3.2.19 on 2024-06-24 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0002_alter_pagamentoboleto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
