# Generated by Django 4.2 on 2023-06-06 23:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0008_delete_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('valor_chave', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CELULAR', 'CELULAR'), ('CNPJ', 'CNPJ'), ('CPF', 'CPF'), ('EMAIL', 'EMAIL'), ('EVP', 'EVP')], max_length=50)),
                ('conta_corrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.contacorrente')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
